import { BaseContent } from "@/modules/BaseContent";
import { Footer } from "@/modules/Footer";
import { Header } from "@/modules/Header";
import { StoreProvider } from "@/redux/StoreProvider";
import { Inter } from "next/font/google";
import "./globals.css";
import styles from "./styles.module.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Главная страница",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <div className={styles.container}>
              <Header className={styles.header}></Header>
              <BaseContent className={styles.baseContent}>{children}</BaseContent>
              <Footer className={styles.footer}></Footer>
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
